---
title: "Global Mortality"
author: "dataGP-UK"
date: "13/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r load_data}
load("2018_04_16/data/grouped_mortality.rda")
```

```{r manipulate_data}
# filter data by regions
## select regions of interest and create vector to subset dataset with
regions <- c(2,4,5,8,9,14,18,19,20,21,22,25,27)
regions <- unique(grouped_mortality$country)[regions]

# subset dataset using regions vector to filter
regional_mortality <- 
  grouped_mortality %>% 
  filter(country %in% regions)

# create a list of causes of death grouped into broader areas
## create vector of all mortality variable names
causes <- 
  regional_mortality %>% 
  select(-c(1:3)) %>% 
  names()
## create list by subsetting causes vector
all_causes <- list("chronic_disease" = causes[c(1,3,4,5,10,12,13,22)], 
                "cancers" = causes[2], 
                "infectious_disease" = causes[c(6,8,11,14,16,19,24,26)], 
                "neonatal_maternal" = causes[c(7,21)], 
                "unnatural" = causes[c(9,15,17,18,20,23,25,27,28,29,30,31)], 
                "unspecified" = causes[32])

# show mortality rates for each of the groups from all_causes list.
## create vector to use to select columns with grouped data 
new_groups <- names(all_causes)
## use each item of all_causes list to subset dataframe prior to rowSums()
regional_mortality<- 
  regional_mortality %>% 
  mutate(chronic_disease = rowSums(.[all_causes[["chronic_disease"]]]),
         infectious_disease = rowSums(.[all_causes[["infectious_disease"]]]),
         neonatal_maternal = rowSums(.[all_causes[["neonatal_maternal"]]]),
         unnatural = rowSums(.[all_causes[["unnatural"]]], na.rm = TRUE)) %>% 
  select(country, year, all_of(new_groups))

```

```{r line_plots_1}
cause <- names(regional_mortality[c(3:8)])

regional_mortality_long <- 
  regional_mortality %>% 
  pivot_longer(data = ., cols = 3:8, names_to = "cause", values_to = "percent")


```

```{r line_plots_2}
map(cause, function(x){
  regional_mortality_long %>% 
  filter(cause %in% x) %>% 
    mutate(country = fct_reorder(country, 
                                 percent, 
                                 tail, 
                                 n = 1, 
                                 .desc = TRUE )) %>%
  ggplot(aes(x = year, y = percent))+
  geom_line(aes(colour = country))+
  labs(title = x)
})
```

```{r bar_plots}

filtered <- regional_mortality_long %>% 
  filter(country %in% c("North America", "Western Europe", "South Asia", 
                        "East Asia", "Sub-Saharan Africa", 
                        "North Africa and Middle East")) %>% 
  mutate(country = as_factor(country)) %>% 
  mutate(country = fct_relevel(country,
        c("Sub-Saharan Africa", "South Asia", "North Africa and Middle East",
           "East Asia","North America", "Western Europe" )))

filtered %>%
  ggplot(aes(x = year, y = percent, fill = cause))+
  geom_col(position = "fill", width = 1)+
  facet_wrap(~ country)+
  theme_bw()+
  scale_y_continuous(labels = scales::"percent")+
  labs(title = "Pattern of mortality in developing countries approaching that in developed",
       subtitle = "Sub-Saharan Africa remains different with mortality from infectious disease & neonatal death still high",
       y = "Percentage of deaths",
       x = "Year",
       caption = "Data from github.com/rfordatascience/tidytuesday/tree/master/data/2018/2018-04-16")+
  scale_fill_discrete(name = "Causes of death",
                      labels = c("Cancers", "Chronic Diseases", 
                                 "Infectious Diseases", "Neonatal & Maternal",
                                 "Unnatural", "Unspecified"))




```

```{r}
ggsave("2018_04_16/output/global_mortality_1.png", width = 10, height = 5)
```
